### ISSUE TITLE
how to show local image

### ISSUE THREAD

**Issue by musicode** [merryjs/photo-viewer#21]
In a chat app, if I send an image message, the receiver need a remote image, but I just need a local image.

**Comment by bang88** [comment]
Not support local image this moment.

**Comment by musicode** [comment]
local image is so common.

When I send an image, first I need to upload the image, if upload failed, I have no remote image url, at this time, if I press the image, how can i do that...

**Comment by bang88** [comment]
Well local image are different from remote image, maybe this feature can implement using RCTImage loader but right now can not figure out how to do it.  I think most of your local image are not in the Assets just relative image ?

If your image a Named image then it should not too hard to implement this functionality, otherwise will do more work for different scenes.

**Comment by musicode** [comment]
Local image is common in the photo library.

the `<Image />` component can't zoom and drag by guesture. ...

**Comment by musicode** [comment]
Thanks!

**Comment by bang88** [comment]
Good news, you can install the latest version for test local image , if you have an image come from Photo library, then you should pass the url like below:

```js
{
    url:  photo.uri
}
```

**Comment by musicode** [comment]
niubility

**Comment by bang88** [comment]
#24
